package DpiDump;
import java.util.LinkedList;
import java.util.List;

import Common.CsvDumper;
import Common.CsvLoader;
import Common.RandUtils;
import Common.RandomCollection;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class DpiDumpGen {
		
	public int gen(String appFilePath, String appProtoFilePath, String ipProtoFilePath) {
		RandomCollection<String> mapApp = CsvLoader.load(appFilePath);
		RandomCollection<String> mapAppProto = CsvLoader.load(appProtoFilePath);
		//RandomCollection<String> mapIpProto = CsvLoader.load(ipProtoFilePath);
		
		List<Record> list = new LinkedList<Record>();
		for (int i = 0 ; i < 10000; i++) {
			Record rec = new Record();
			
			rec.setUserImsi(RandUtils.nextIntString(15));
			rec.setUserImei(RandUtils.nextIntString(15));
			       
			rec.setNwApn(RandUtils.nextDomainName(RandUtils.nextInt(2,4)));
			rec.setNwChargingCharacteristics(RandUtils.nextIntString(12));
			rec.setNwRatType(RandUtils.nextRat());
			rec.setNwMcc(RandUtils.nextIntString(3));
			rec.setNwMnc(RandUtils.nextIntString(3));
			rec.setNwCi(RandUtils.nextIntString(2));
			rec.setNwEci(RandUtils.nextIntString(3));
			rec.setNwLac(RandUtils.nextIntString(3));
			rec.setNwSac(RandUtils.nextIntString(3));
			rec.setNwRac(RandUtils.nextIntString(3));
			rec.setNwTac(RandUtils.nextIntString(5));
			
			rec.setAppName(mapApp.next());
			rec.setAppProto(mapAppProto.next());
			
			rec.setDestinationIpAddress(RandUtils.nextIpv4());
			rec.setDestinationPort(RandUtils.nextInt(0,65535));
			
			rec.setDownlinkBytes(RandUtils.nextNormal());
			rec.setDownlinkPkt(RandUtils.nextNormal());
			rec.setUplinkBytes(RandUtils.nextNormal());
			rec.setUplinkPkt(RandUtils.nextNormal());
			
			rec.setIsTetheringDetected(RandUtils.nextBoolean()?"true":"false");
			
			rec.setUrl(RandUtils.nextUrl());
			
			//System.out.println(str);
			list.add(rec);
		}
		
		try {
			CsvDumper dumper = new CsvDumper();
			dumper.dump(list, "./dpi-dump.csv");
		} catch (Exception e) {
			e.printStackTrace();
		}
        return 0;
    }
}
