/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class DpiDumpGen {
	String appFilePath;
	String outputFilePath;
		
	public void setAppFilePath(String appFilePath) {
		this.appFilePath = appFilePath;
	}

	public void setOutputFilePath(String outputFilePath) {
		this.outputFilePath = outputFilePath;
	}

	public int gen() {
		
        return 0;
    }
}
