/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class DpiDumpGen {
	String outputFilePath;
	
	
	
    public void setOutputFilePath(String outputFilePath) {
		this.outputFilePath = outputFilePath;
	}



	public int gen() {
        return 0;
    }
}
