/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import Common.Config;

import static org.junit.Assert.*;

public class DpiDumpGenTest {
    @Test public void testSomeLibraryMethod() {
        DpiDumpGen gen = new DpiDumpGen();
        
        String appFilePath = Config.getAppFilePath();
        gen.setAppFilePath(appFilePath);
        
        String outputFilePath = Config.getOutputFilePath();
        gen.setOutputFilePath(outputFilePath);
        
        assertTrue("gen should return 0", gen.gen()==0);
        
        System.out.printf("Dumping into %s\n", outputFilePath);
    }
}
